version: "3.1"

volumes:
  pg_project:

networks:
  pg_project:
    driver: bridge

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    links:
      - db:db
    networks:
      - pg_project
    restart: always
  db:
    image: postgres
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - pg_project
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
    volumes:
      - pg_project:/var/lib/postgresql/data


