version: "3.1"

volumes:
  pg_project:

networks:
  pg_project:
    driver: bridge

services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      - pg_db
    links:
      - pg_db:pg_db
    networks:
      - pg_project
    restart: always
  pg_db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - pg_project
    environment:
      - DB_PASSWORD=admin
      - DB_USER=admin
      - DB_NAME=project
    volumes:
      - pg_project:/var/lib/postgresql/data
